"""
One historical fact per calendar day — all 366 days including Feb 29.
Facts are chosen to connect with SigmoCatClash category themes:
food, animals, science, geography, sports, music, art, and famous people.

Usage:
    from utils.categoryhistory import get_today_history
    fact = get_today_history(local_dt)   # pass a timezone-aware datetime
"""

from datetime import datetime

# ── 366 daily facts ────────────────────────────────────────────────────────────
# Key: (month, day)   Value: one sentence (≤120 chars for clean embed display)

HISTORY: dict[tuple[int, int], str] = {

    # ── January ────────────────────────────────────────────────────────────────
    (1,  1): "Julius Caesar introduced the Julian calendar in 45 BC, giving January 1 its place as New Year's Day.",
    (1,  2): "Isaac Asimov, who coined the word 'robotics' and wrote the Three Laws, was born on this day in 1920.",
    (1,  3): "Louis Braille, inventor of the tactile reading system used by blind people worldwide, was born today in 1809.",
    (1,  4): "Sir Isaac Newton, who described gravity after observing a falling apple, was born in Woolsthorpe on this day in 1643.",
    (1,  5): "The x-ray was publicly announced by Wilhelm Röntgen today in 1896, revolutionising medical diagnosis.",
    (1,  6): "The first Sherlock Holmes story was published in Beeton's Christmas Annual on this day in 1887.",
    (1,  7): "The first US patent for a practical typewriter was issued to Christopher Sholes on this day in 1868.",
    (1,  8): "Elvis Presley, 'The King of Rock and Roll,' was born in Tupelo, Mississippi on this day in 1935.",
    (1,  9): "Steve Jobs unveiled the first iPhone at Macworld in San Francisco on this day in 2007.",
    (1, 10): "The world's first underground railway — the London Metropolitan — opened to passengers on this day in 1863.",
    (1, 11): "The first insulin injection to treat diabetes was administered to 14-year-old Leonard Thompson on this day in 1922.",
    (1, 12): "Agatha Christie disappeared mysteriously for 11 days — the most baffling case of 1926 — beginning on this date.",
    (1, 13): "Chess arrived in Europe from Persia around the 9th century; the first recorded European tournament was held in 1575.",
    (1, 14): "Whisky was first officially distilled in Scotland by Friar John Cor on this day in 1494 — the oldest recorded batch.",
    (1, 15): "Martin Luther King Jr., civil rights leader and Nobel Peace Prize winner, was born in Atlanta on this day in 1929.",
    (1, 16): "Prohibition began in the United States on this day in 1920, banning alcohol for 13 years.",
    (1, 17): "Benjamin Franklin, who proved lightning is electricity by flying a kite in a thunderstorm, was born today in 1706.",
    (1, 18): "Roald Amundsen's team completed the first South Pole expedition in 1911, beating Scott by 34 days.",
    (1, 19): "The world's first purpose-built pizzeria, Antica Pizzeria Port'Alba in Naples, opened around this date in 1830.",
    (1, 20): "John F. Kennedy was inaugurated as the 35th US President on this day in 1961, inspiring a generation.",
    (1, 21): "The first Concorde supersonic passenger service departed Paris and London simultaneously on this day in 1976.",
    (1, 22): "Queen Victoria, Britain's longest-reigning monarch at the time, died on this day in 1901 after 63 years on the throne.",
    (1, 23): "The first Winter Olympics opened in Chamonix, France on this day in 1924, featuring 16 nations.",
    (1, 24): "Gold was discovered at Sutter's Mill, California on this day in 1848, sparking the great Gold Rush.",
    (1, 25): "Robert Burns, Scotland's national poet who gave the world 'Auld Lang Syne,' was born today in 1759.",
    (1, 26): "India became a democratic republic on this day in 1950, adopting the world's longest written constitution.",
    (1, 27): "Wolfgang Amadeus Mozart, who wrote over 600 musical works beginning at age 5, was born today in 1756.",
    (1, 28): "The first McDonald's franchise outside North America opened in the Netherlands on this day in 1971.",
    (1, 29): "The first cardboard cereal box — containing corn flakes — was invented by John Harvey Kellogg around this date in 1894.",
    (1, 30): "Mahatma Gandhi, who led India's independence through non-violence, was assassinated in New Delhi on this day in 1948.",
    (1, 31): "The world's first public demonstration of television was given by John Logie Baird in London on this day in 1926.",

    # ── February ───────────────────────────────────────────────────────────────
    (2,  1): "The first issue of the Encyclopædia Britannica was published in Edinburgh on this day in 1768.",
    (2,  2): "Groundhog Day — Punxsutawney Phil has predicted the weather in the US since 1887, with about 40% accuracy.",
    (2,  3): "The first issue of National Geographic Magazine was published on this day in 1888.",
    (2,  4): "Facebook launched from a Harvard dorm room on this day in 2004, connecting billions within a decade.",
    (2,  5): "The modern chocolate bar was invented by Joseph Fry in Bristol, England around this day in 1847.",
    (2,  6): "Babe Ruth, perhaps baseball's greatest player ever, was born in Baltimore on this day in 1895.",
    (2,  7): "Charles Dickens, who wrote Oliver Twist and A Christmas Carol, was born in Portsmouth on this day in 1812.",
    (2,  8): "Jules Verne, who envisioned submarines and space travel before they existed, was born today in 1828.",
    (2,  9): "Momofuku Ando invented instant ramen noodles in 1958; over 100 billion servings are now eaten worldwide each year.",
    (2, 10): "The first commercially frozen vegetables went on sale in US grocery stores on this day in 1930.",
    (2, 11): "Thomas Edison — inventor of the lightbulb, phonograph, and motion camera — was born today in 1847.",
    (2, 12): "Abraham Lincoln, who ended slavery in the United States, was born in a log cabin in Kentucky on this day in 1809.",
    (2, 13): "The first world tennis championship was played at the Queen's Club in London on this day in 1900.",
    (2, 14): "Valentine's Day cards were first mass-produced by Esther Howland of Worcester, Massachusetts in the 1840s.",
    (2, 15): "Galileo Galilei, who first observed the moons of Jupiter, was born in Pisa, Italy on this day in 1564.",
    (2, 16): "The first issue of Sports Illustrated was published in New York on this day in 1954.",
    (2, 17): "The world's first submarine to sink an enemy warship, the H.L. Hunley, made history on this day in 1864.",
    (2, 18): "Pluto was discovered by 24-year-old astronomer Clyde Tombaugh at Lowell Observatory on this day in 1930.",
    (2, 19): "Nicolaus Copernicus, who proved Earth orbits the Sun, was born in Royal Prussia on this day in 1473.",
    (2, 20): "John Glenn became the first American to orbit Earth, circling it three times on this day in 1962.",
    (2, 21): "The Washington Monument in Washington DC officially opened to the public on this day in 1885.",
    (2, 22): "George Washington, the first US President, was born in Virginia on this day in 1732.",
    (2, 23): "Samuel Pepys began his famous diary on this day in 1660, creating an invaluable record of 17th-century London life.",
    (2, 24): "The first 911 emergency telephone call was made in Haleyville, Alabama on this day in 1968.",
    (2, 25): "The first Grammy Awards ceremony was held in Beverly Hills and New York City on this day in 1959.",
    (2, 26): "Victor Hugo, author of Les Misérables and The Hunchback of Notre-Dame, was born today in 1802.",
    (2, 27): "John Steinbeck, who wrote The Grapes of Wrath and Of Mice and Men, was born in Salinas, California today in 1902.",
    (2, 28): "Thomas Edison patented his phonograph — a machine that could record and play back the human voice — on this day in 1878.",
    (2, 29): "Leap Day occurs only once every four years; it was added by Julius Caesar's calendar reform to keep seasons aligned.",

    # ── March ──────────────────────────────────────────────────────────────────
    (3,  1): "Yellowstone became the world's first national park on this day in 1872, protecting its geysers and wildlife.",
    (3,  2): "Dr. Seuss (Theodor Geisel), beloved author of The Cat in the Hat, was born in Springfield today in 1904.",
    (3,  3): "The US national anthem 'The Star-Spangled Banner' was officially adopted by Congress on this day in 1931.",
    (3,  4): "Vermont became the first US state to abolish adult slavery in its constitution, on this day in 1777.",
    (3,  5): "The first ever rugby match played under formal rules took place at Raeburn Place in Edinburgh on this day in 1871.",
    (3,  6): "Oreo cookies were introduced by the National Biscuit Company on this day in 1912 — now the world's best-selling biscuit.",
    (3,  7): "Alexander Graham Bell was awarded the patent for the telephone on this day in 1876.",
    (3,  8): "International Women's Day — marking women's achievements worldwide — was first officially observed on this day in 1911.",
    (3,  9): "Yuri Gagarin, the first human being to travel to space, was born in Klushino, Russia on this day in 1934.",
    (3, 10): "Alexander Graham Bell made the world's first telephone call — to his assistant Thomas Watson — on this day in 1876.",
    (3, 11): "The World Health Organization was founded on this day in 1948 to promote global public health.",
    (3, 12): "The World Wide Web was proposed by Tim Berners-Lee in a memo to his CERN manager on this day in 1989.",
    (3, 13): "Uranus was discovered by astronomer William Herschel on this day in 1781 — the first planet found with a telescope.",
    (3, 14): "Albert Einstein, whose equation E=mc² unlocked nuclear physics, was born in Ulm, Germany on this day in 1879.",
    (3, 15): "Julius Caesar was assassinated on the Ides of March in 44 BC, after being warned to 'beware the Ides of March.'",
    (3, 16): "Michelangelo Buonarroti, sculptor of David and painter of the Sistine Chapel, died in Rome on this day in 1564.",
    (3, 17): "St. Patrick's Day — celebrating Ireland's patron saint who reportedly drove snakes from Ireland — has been observed since the 9th century.",
    (3, 18): "The first spacewalk was performed by Soviet cosmonaut Alexei Leonov on this day in 1965, lasting 12 minutes.",
    (3, 19): "The first modern vending machine in the US — dispensing postcards — was introduced in New York on this day in 1888.",
    (3, 20): "The vernal equinox — first day of spring in the Northern Hemisphere — typically falls on this date each year.",
    (3, 21): "Johann Sebastian Bach, master of the fugue and composer of the Brandenburg Concertos, was born today in 1685.",
    (3, 22): "The world's largest freshwater lake by volume, Lake Baikal in Siberia, contains about 20% of Earth's unfrozen surface fresh water.",
    (3, 23): "The first transatlantic weather forecast using telegraph was issued on this day in 1848 from Washington DC.",
    (3, 24): "Harry Houdini performed his famous Milk Can Escape for the first time in front of a paying audience on this day in 1908.",
    (3, 25): "The first chocolate Easter eggs were made in France and Germany around this date in the early 19th century.",
    (3, 26): "Ludwig van Beethoven, who composed his magnificent 9th Symphony while completely deaf, died on this day in 1827.",
    (3, 27): "French doctor René Laennec invented the stethoscope on this day in 1816 by rolling paper into a tube to hear a patient's heart.",
    (3, 28): "The Three Mile Island nuclear accident — America's most serious nuclear incident — began on this day in 1979.",
    (3, 29): "Chinese farmers accidentally discovered the Terracotta Army — 8,000 life-size clay soldiers — near Xi'an on this day in 1974.",
    (3, 30): "Vincent van Gogh, who painted over 900 artworks in a decade including Starry Night, was born today in 1853.",
    (3, 31): "The Eiffel Tower was inaugurated in Paris on this day in 1889, standing as the world's tallest structure for 41 years.",

    # ── April ──────────────────────────────────────────────────────────────────
    (4,  1): "April Fools' Day may trace back to 1564 France, when New Year's Day moved from April 1 to January 1.",
    (4,  2): "Hans Christian Andersen, author of The Little Mermaid and The Ugly Duckling, was born today in 1805.",
    (4,  3): "The Pony Express mail service launched its first ride from Missouri to California on this day in 1860.",
    (4,  4): "Martin Luther King Jr. was assassinated at the Lorraine Motel in Memphis, Tennessee on this day in 1968.",
    (4,  5): "Joseph Lister published his groundbreaking antiseptic surgery methods on this day in 1867, transforming medicine.",
    (4,  6): "The first modern Olympic Games opened in Athens, Greece on this day in 1896, with 241 athletes from 14 nations.",
    (4,  7): "World Health Day — marked by the UN — falls on this date, the founding anniversary of the WHO in 1948.",
    (4,  8): "The Venus de Milo, an ancient Greek marble sculpture, was discovered on the island of Milos on this day in 1820.",
    (4,  9): "The American Civil War ended when Confederate General Robert E. Lee surrendered to Ulysses S. Grant on this day in 1865.",
    (4, 10): "The Titanic departed Southampton on its ill-fated maiden voyage on this day in 1912.",
    (4, 11): "The world's first open-heart surgery using a heart-lung machine was performed in Philadelphia on this day in 1953.",
    (4, 12): "Yuri Gagarin became the first human in space, orbiting Earth once in 108 minutes on this day in 1961.",
    (4, 13): "Thomas Jefferson, who wrote the Declaration of Independence and founded the University of Virginia, was born today in 1743.",
    (4, 14): "The Titanic struck an iceberg and sank on this day in 1912, claiming over 1,500 lives in the North Atlantic.",
    (4, 15): "Leonardo da Vinci — painter, sculptor, architect, musician, and scientist — was born in Vinci, Italy today in 1452.",
    (4, 16): "Charlie Chaplin, whose silent film comedy shaped modern cinema, was born in London on this day in 1889.",
    (4, 17): "Apollo 13 returned safely to Earth after an oxygen tank explosion aborted its Moon landing on this day in 1970.",
    (4, 18): "Albert Einstein died in Princeton, New Jersey on this day in 1955, having given the world the theory of relativity.",
    (4, 19): "The first Boston Marathon was run on this day in 1897, won by John McDermott of New York in 2 hours 55 minutes.",
    (4, 20): "The first bottled Coca-Cola went on sale commercially on this day in 1894 in Vicksburg, Mississippi.",
    (4, 21): "Rome, the 'Eternal City,' was traditionally founded on this day in 753 BC according to Roman mythology.",
    (4, 22): "Earth Day — the world's largest environmental movement — was first observed on this day in 1970.",
    (4, 23): "William Shakespeare, the world's most performed playwright, was born in Stratford-upon-Avon on this day in 1564.",
    (4, 24): "The Hubble Space Telescope was launched aboard Space Shuttle Discovery on this day in 1990.",
    (4, 25): "The double-helix structure of DNA was published in Nature by Watson and Crick on this day in 1953.",
    (4, 26): "John James Audubon, whose detailed bird paintings catalogued 435 North American species, was born today in 1785.",
    (4, 27): "The modern zipper — originally called the 'hookless fastener' — was patented by Gideon Sundback on this day in 1913.",
    (4, 28): "Thor Heyerdahl launched his Kon-Tiki balsa raft from Peru, proving ancient Polynesians could have sailed from South America.",
    (4, 29): "Duke Ellington, who composed over 1,000 pieces and revolutionised jazz, was born in Washington DC today in 1899.",
    (4, 30): "The Louisiana Territory was purchased from France for $15 million — roughly 3 cents per acre — on this day in 1803.",

    # ── May ────────────────────────────────────────────────────────────────────
    (5,  1): "International Workers' Day traces back to the Haymarket Affair in Chicago, which occurred on this day in 1886.",
    (5,  2): "Leonardo da Vinci died in Amboise, France on this day in 1519, leaving behind the Mona Lisa and 7,000 pages of notebooks.",
    (5,  3): "The first postage stamp — the 'Penny Black' — went on sale in the United Kingdom on this day in 1840.",
    (5,  4): "Star Wars Day ('May the Fourth be with you') celebrates the Star Wars franchise, first released in 1977.",
    (5,  5): "Cinco de Mayo commemorates the Battle of Puebla where Mexico defeated France on this day in 1862.",
    (5,  6): "Roger Bannister became the first person to run a mile in under 4 minutes (3:59.4) on this day in 1954.",
    (5,  7): "Johannes Brahms, composer of the famous Lullaby (Wiegenlied), was born in Hamburg on this day in 1833.",
    (5,  8): "The first Coca-Cola was served as a patent medicine at Jacob's Pharmacy in Atlanta, Georgia on this day in 1886.",
    (5,  9): "The world's first Mother's Day celebration was held in Grafton, West Virginia on this day in 1908.",
    (5, 10): "The Transcontinental Railroad linking the US coast to coast was completed at Promontory Summit, Utah on this day in 1869.",
    (5, 11): "Salvador Dalí, surrealist painter of The Persistence of Memory and its melting clocks, was born today in 1904.",
    (5, 12): "Florence Nightingale, who founded modern nursing and improved hospital hygiene, was born in Florence today in 1820.",
    (5, 13): "Stevie Wonder, who has been blind since birth and has won 25 Grammy Awards, was born on this day in 1950.",
    (5, 14): "The state of Israel declared independence on this day in 1948, becoming the first new Jewish state in 2,000 years.",
    (5, 15): "Nylon stockings went on sale across the United States on this day in 1940, selling 4 million pairs on day one.",
    (5, 16): "The first Academy Awards ceremony was held at the Hollywood Roosevelt Hotel on this day in 1929, lasting only 15 minutes.",
    (5, 17): "The first FIFA World Cup kicked off in Uruguay on this day in 1930, with 13 nations competing.",
    (5, 18): "Mount St. Helens volcano in Washington State erupted violently on this day in 1980, flattening 230 square miles of forest.",
    (5, 19): "The Louvre Museum in Paris — now the world's most visited — opened to the public on this day in 1793.",
    (5, 20): "Charles Lindbergh completed the first non-stop solo transatlantic flight, landing in Paris on this day in 1927.",
    (5, 21): "Clara Barton, who founded the American Red Cross, was born in Oxford, Massachusetts on this day in 1821.",
    (5, 22): "Arthur Conan Doyle, creator of the world's most famous fictional detective Sherlock Holmes, was born today in 1859.",
    (5, 23): "Carl Linnaeus, who invented the scientific naming system for all living organisms, was born in Sweden today in 1707.",
    (5, 24): "Queen Victoria — the monarch who gave her name to an era — was born on this day in 1819.",
    (5, 25): "The original Star Wars film premiered in US cinemas on this day in 1977, changing science fiction forever.",
    (5, 26): "The Golden Gate Bridge in San Francisco opened to pedestrians on this day in 1937.",
    (5, 27): "Rachel Carson, whose book Silent Spring launched the global environmental movement, was born today in 1907.",
    (5, 28): "The first test-tube ice cream using liquid nitrogen was demonstrated by Heston Blumenthal on this day in 1997.",
    (5, 29): "Edmund Hillary and Tenzing Norgay became the first people to summit Mount Everest on this day in 1953.",
    (5, 30): "The first Indianapolis 500 motor race — at a then-outrageous average speed of 75 mph — was held on this day in 1911.",
    (5, 31): "Clint Eastwood, iconic actor and director famous for spaghetti westerns and Dirty Harry, was born today in 1930.",

    # ── June ───────────────────────────────────────────────────────────────────
    (6,  1): "Marilyn Monroe performed her iconic birthday serenade 'Happy Birthday, Mr. President' to JFK on this day in 1962.",
    (6,  2): "Queen Elizabeth II was crowned at Westminster Abbey on this day in 1953, becoming the first televised coronation.",
    (6,  3): "Ed White became the first American to walk in space on this day in 1965, tethered to Gemini 4 for 23 minutes.",
    (6,  4): "The Battle of Midway — the decisive naval turning point of the Pacific War — began on this day in 1942.",
    (6,  5): "World Environment Day — established by the United Nations to protect nature globally — is observed on this day.",
    (6,  6): "D-Day: 156,000 Allied troops landed on Normandy's beaches in the largest seaborne invasion in history on this day in 1944.",
    (6,  7): "Alan Turing, who cracked the Nazi Enigma code and founded computer science, was born in London on this day in 1912.",
    (6,  8): "World Ocean Day reminds us that oceans produce over 50% of Earth's oxygen and absorb 30% of its CO₂.",
    (6,  9): "The first cricket Test match in history was played in Melbourne between Australia and England on this day in 1877.",
    (6, 10): "Prince, the genre-defying musician who sold over 100 million records, was born in Minneapolis on this day in 1958.",
    (6, 11): "Jacques Cousteau, who co-invented SCUBA and introduced the ocean to millions through TV, was born today in 1910.",
    (6, 12): "Anne Frank received her diary as a 13th birthday gift on this day in 1942 — she would soon begin her famous entries.",
    (6, 13): "The Miranda rights — 'you have the right to remain silent' — were established by the US Supreme Court on this day in 1966.",
    (6, 14): "Ernesto 'Che' Guevara, revolutionary and global countercultural icon, was born in Rosario, Argentina today in 1928.",
    (6, 15): "Magna Carta — the cornerstone of democracy and human rights — was sealed at Runnymede, England on this day in 1215.",
    (6, 16): "The Soweto Uprising — a turning point in South Africa's anti-apartheid movement — began on this day in 1976.",
    (6, 17): "The Watergate break-in that ultimately led to President Nixon's resignation occurred on this day in 1972.",
    (6, 18): "Amelia Earhart became the first woman to fly solo across the Atlantic, completing the journey on this day in 1928.",
    (6, 19): "Juneteenth marks the day enslaved people in Texas finally learned of their emancipation on this day in 1865.",
    (6, 20): "The summer solstice — the longest day of the year — typically falls on or near this date in the Northern Hemisphere.",
    (6, 21): "Stonehenge in England, built around 3000 BC, is perfectly aligned with the sunrise on the summer solstice today.",
    (6, 22): "The Wimbledon tennis tournament held its first championship on this day in 1877, won by Spencer Gore.",
    (6, 23): "The concept of the computer was described by Alan Turing in his landmark paper published on this day in 1936.",
    (6, 24): "Midsummer — celebrated across Scandinavia with bonfires, flowers, and the world's strongest coffee tradition — falls around today.",
    (6, 25): "The Korean War began when North Korea invaded South Korea on this day in 1950.",
    (6, 26): "The United Nations Charter was signed by 50 nations in San Francisco on this day in 1945.",
    (6, 27): "Helen Keller, who was deaf and blind from age 19 months yet earned a university degree, was born today in 1880.",
    (6, 28): "Archduke Franz Ferdinand was assassinated in Sarajevo on this day in 1914, triggering World War I.",
    (6, 29): "The Globe Theatre in London — where Shakespeare's plays premiered — burned down during a performance on this day in 1613.",
    (6, 30): "The microwave oven was invented by accident when engineer Percy Spencer's chocolate bar melted near a radar device in 1945.",

    # ── July ───────────────────────────────────────────────────────────────────
    (7,  1): "Canada Day — celebrating Confederation on this day in 1867 — makes Canada one of the world's oldest modern democracies.",
    (7,  2): "Amelia Earhart disappeared over the Pacific Ocean during her round-the-world flight attempt on this day in 1937.",
    (7,  3): "The Battle of Gettysburg — the bloodiest of the American Civil War — ended on this day in 1863.",
    (7,  4): "The United States Declaration of Independence was formally adopted by the Continental Congress on this day in 1776.",
    (7,  5): "The bikini swimsuit was introduced by French designer Louis Réard at a Paris pool on this day in 1946.",
    (7,  6): "The Dalai Lama — spiritual leader of Tibetan Buddhism and Nobel Peace Prize winner — was born today in 1935.",
    (7,  7): "Live Aid — raising $125 million for African famine relief — was performed simultaneously in London and Philadelphia on this day in 1985.",
    (7,  8): "The Liberty Bell in Philadelphia cracked catastrophically while tolling on this day in 1835.",
    (7,  9): "Argentinian independence from Spanish colonial rule was declared at the Tucumán Congress on this day in 1816.",
    (7, 10): "Marcel Proust, who wrote the world's longest novel (In Search of Lost Time at 1.5 million words), was born today in 1871.",
    (7, 11): "World Population Day — established by the UN in 1989 — marks the day Earth's population first hit 5 billion.",
    (7, 12): "Henry David Thoreau, who lived alone in the woods for two years to observe nature and wrote Walden, was born today in 1817.",
    (7, 13): "The first Wimbledon women's final was played on this day in 1884, won by Maud Watson of England.",
    (7, 14): "Bastille Day — France's national holiday celebrating the 1789 French Revolution — falls on this date each year.",
    (7, 15): "Rembrandt van Rijn, one of history's greatest portrait painters, was born in Leiden, Netherlands on this day in 1606.",
    (7, 16): "Apollo 11 — carrying Neil Armstrong, Buzz Aldrin, and Michael Collins — launched from Cape Kennedy on this day in 1969.",
    (7, 17): "Disneyland, the world's original major theme park, opened in Anaheim, California on this day in 1955.",
    (7, 18): "Nelson Mandela — who spent 27 years in prison and became South Africa's first black president — was born today in 1918.",
    (7, 19): "The first women's rights convention in the US was held in Seneca Falls, New York on this day in 1848.",
    (7, 20): "Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon on this day in 1969.",
    (7, 21): "Ernest Hemingway, Nobel Prize-winning author of The Old Man and the Sea, was born today in 1899.",
    (7, 22): "Gregor Mendel, whose pea plant experiments founded modern genetics, was born in Hynčice on this day in 1822.",
    (7, 23): "The Tour de France — the world's most prestigious cycling race — was first held on this day in 1903.",
    (7, 24): "Simón Bolívar, who liberated six South American nations from Spanish rule, was born in Caracas today in 1783.",
    (7, 25): "The first test-tube baby (Louise Brown) was born in Oldham, England on this day in 1978, to worldwide amazement.",
    (7, 26): "Mick Jagger and Keith Richards of the Rolling Stones first met on a train platform on this day in 1961.",
    (7, 27): "The Korean War armistice — ending three years of fighting — was signed at Panmunjom on this day in 1953.",
    (7, 28): "Beethoven's 5th Symphony, beginning with its iconic four-note motif (da-da-da-DUM), premiered in Vienna on this day in 1808.",
    (7, 29): "NASA was established as the United States' civilian space agency on this day in 1958.",
    (7, 30): "Henry Ford, who made cars affordable for ordinary people by inventing the assembly line, was born today in 1863.",
    (7, 31): "J.K. Rowling, who wrote the Harry Potter series — the best-selling book series of all time — was born today in 1965.",

    # ── August ─────────────────────────────────────────────────────────────────
    (8,  1): "Herman Melville, author of Moby-Dick — the great American novel about a white whale — was born today in 1819.",
    (8,  2): "The pencil was first mass-produced in Cumberland, England around this date in 1662, using a newly discovered graphite deposit.",
    (8,  3): "Christopher Columbus set sail from Palos de la Frontera, Spain toward the Americas on this day in 1492.",
    (8,  4): "Barack Obama, the 44th US President and first African American to hold the office, was born today in 1961.",
    (8,  5): "Neil Armstrong, the first human to walk on the Moon, was born in Wapakoneta, Ohio on this day in 1930.",
    (8,  6): "The first atomic bomb was dropped on Hiroshima, Japan on this day in 1945.",
    (8,  7): "The first transatlantic telegraph cable was completed, sending a message between Newfoundland and Ireland on this day in 1858.",
    (8,  8): "The 1936 Berlin Olympics — at which Jesse Owens won four gold medals — opened on this day.",
    (8,  9): "The second atomic bomb was dropped on Nagasaki, Japan on this day in 1945.",
    (8, 10): "The Smithsonian Institution — the world's largest museum complex with 19 museums — was founded on this day in 1846.",
    (8, 11): "Alex Haley, whose book Roots traced one family's African American heritage back to Gambia, was born today in 1921.",
    (8, 12): "The IBM Personal Computer went on sale on this day in 1981, beginning the era of home computing.",
    (8, 13): "The Berlin Wall — dividing East and West Germany for 28 years — began construction overnight on this day in 1961.",
    (8, 14): "Japan surrendered, ending World War II, on this day in 1945 — V-J Day (Victory over Japan Day).",
    (8, 15): "India gained independence from British rule on this day in 1947, the moment Nehru described as 'a tryst with destiny.'",
    (8, 16): "Elvis Presley, 'The King of Rock and Roll,' died at his Graceland estate in Memphis on this day in 1977.",
    (8, 17): "Indonesia declared independence from the Netherlands on this day in 1945.",
    (8, 18): "The 19th Amendment giving women the right to vote was certified in the US on this day in 1920.",
    (8, 19): "The first manned hydrogen balloon flew over Paris, reaching 3,000 metres on this day in 1783.",
    (8, 20): "The Trans-Siberian Railway — the world's longest at 9,289 km — was fully completed on this day in 1904.",
    (8, 21): "Hawaii officially became the 50th US state on this day in 1959.",
    (8, 22): "The first Geneva Convention — establishing rules to protect wounded soldiers in war — was signed on this day in 1864.",
    (8, 23): "Coconut, used in cuisines from India to the Caribbean, has been cultivated in South Asia for over 3,000 years.",
    (8, 24): "Mount Vesuvius erupted and buried the Roman city of Pompeii in ash and pumice on this day in 79 AD.",
    (8, 25): "The first Rugby World Cup was held in Australia and New Zealand in 1987, won by the All Blacks — on this day in the final.",
    (8, 26): "Mother Teresa, who dedicated her life to the poorest of the poor in Calcutta, was born in Skopje on this day in 1910.",
    (8, 27): "The eruption of Krakatoa in 1883 — one of the loudest sounds ever recorded — was heard 4,800 km away on this day.",
    (8, 28): "Martin Luther King Jr. delivered his iconic 'I Have a Dream' speech to 250,000 people in Washington DC on this day in 1963.",
    (8, 29): "Coco Chanel, who revolutionised women's fashion with the little black dress and Chanel No. 5, was born today in 1883.",
    (8, 30): "Mary Shelley, who wrote Frankenstein at age 18 and invented modern science fiction, was born in London today in 1797.",
    (8, 31): "The first commercial oil well in the United States began drilling in Titusville, Pennsylvania on this day in 1859.",

    # ── September ──────────────────────────────────────────────────────────────
    (9,  1): "The first Labour Day was celebrated in New York City on this day in 1882 to honour the American worker.",
    (9,  2): "The Great Fire of London began in a baker's shop on Pudding Lane on this day in 1666, destroying 13,200 buildings.",
    (9,  3): "The Treaty of Paris, formally ending the American Revolution, was signed on this day in 1783.",
    (9,  4): "The first email was sent by engineer Ray Tomlinson using the @ symbol in the address on this day in 1971.",
    (9,  5): "Mother Teresa, who won the Nobel Peace Prize in 1979, died in Calcutta on this day in 1997.",
    (9,  6): "The first practical sewing machine patent was granted to Elias Howe on this day in 1846.",
    (9,  7): "Brazil declared independence from Portugal on this day in 1822 — it is now the world's fifth-largest nation.",
    (9,  8): "Star Trek premiered on NBC on this day in 1966, inspiring generations of real-world scientists and engineers.",
    (9,  9): "The Nintendo Game Boy went on sale in North America on this day in 1989, selling over 100 million units.",
    (9, 10): "Mary Wollstonecraft, founder of feminist philosophy and author of A Vindication of the Rights of Woman, died today in 1797.",
    (9, 11): "The September 11 attacks in New York and Washington DC on this day in 2001 claimed nearly 3,000 lives.",
    (9, 12): "Jesse Owens won his fourth gold medal at the Berlin Olympics on this day in 1936, disproving Nazi racial theories.",
    (9, 13): "Roald Dahl, author of Charlie and the Chocolate Factory and The BFG, was born in Llandaff, Wales today in 1916.",
    (9, 14): "Alexander von Humboldt — who founded the science of ecology — was born in Berlin on this day in 1769.",
    (9, 15): "Agatha Christie, the best-selling fiction novelist of all time after the Bible, was born in Torquay today in 1890.",
    (9, 16): "Malaysia gained independence and formed a federation on this day in 1963.",
    (9, 17): "The US Constitution was signed by 39 delegates at the Constitutional Convention in Philadelphia on this day in 1787.",
    (9, 18): "The New York Times published its first edition on this day in 1851 — it remains the US newspaper of record.",
    (9, 19): "The world's first dishwasher patent was granted to Josephine Cochrane of Illinois on this day in 1886.",
    (9, 20): "The first episode of SpongeBob SquarePants aired on Nickelodeon on this day in 1999.",
    (9, 21): "J.R.R. Tolkien published The Hobbit on this day in 1937 — 'In a hole in the ground there lived a hobbit.'",
    (9, 22): "Bilbo Baggins' birthday — Tolkien placed his beloved hobbit's birth on September 22 in The Lord of the Rings.",
    (9, 23): "Neptune was discovered by astronomers using Le Verrier's calculations on this day in 1846.",
    (9, 24): "The first VCR (video cassette recorder) went on sale in the United States on this day in 1977.",
    (9, 25): "The world's first public park — Birkenhead Park in England — designed by Joseph Paxton opened on this day in 1847.",
    (9, 26): "The first televised US presidential debate (Kennedy vs Nixon) was watched by 74 million people on this day in 1960.",
    (9, 27): "The Orient Express luxury train service made its first run from Paris to Istanbul on this day in 1883.",
    (9, 28): "Louis Pasteur, who developed vaccines for rabies and invented pasteurisation of milk, was born today in 1822.",
    (9, 29): "The world's first police force — the Metropolitan Police of London — was established on this day in 1829.",
    (9, 30): "James Dean, the ultimate 1950s film icon, died in a car crash near Paso Robles, California on this day in 1955.",

    # ── October ────────────────────────────────────────────────────────────────
    (10,  1): "World Vegetarian Day — observed today — celebrates the growing global plant-based food movement.",
    (10,  2): "Mahatma Gandhi, who led India to independence through non-violent resistance, was born in Porbandar today in 1869.",
    (10,  3): "Germany was officially reunified — East and West becoming one nation again — on this day in 1990.",
    (10,  4): "Sputnik 1, the first artificial satellite, was launched by the Soviet Union on this day in 1957.",
    (10,  5): "Apple co-founder Steve Jobs died in Palo Alto, California on this day in 2011.",
    (10,  6): "The first sound film, The Jazz Singer with Al Jolson, premiered in New York City on this day in 1927.",
    (10,  7): "The BBC — the world's oldest national broadcaster — launched its first regular television service on this day in 1936.",
    (10,  8): "The Great Chicago Fire began, destroying 3.3 square miles and leaving 100,000 homeless on this day in 1871.",
    (10,  9): "John Lennon, a founding member of The Beatles, was born in Liverpool, England on this day in 1940.",
    (10, 10): "Fiji gained independence from the United Kingdom on this day in 1970.",
    (10, 11): "Eleanor Roosevelt — diplomat, author, and first chair of the UN Human Rights Commission — was born today in 1884.",
    (10, 12): "Christopher Columbus arrived in the Caribbean on this day in 1492, completing 70 days at sea.",
    (10, 13): "The world's longest roller coaster — Steel Dragon 2000 in Japan — opened to passengers on this day in 2000.",
    (10, 14): "Martin Luther King Jr. was awarded the Nobel Peace Prize on this day in 1964, becoming its youngest recipient.",
    (10, 15): "The Galileo spacecraft was launched by NASA toward Jupiter on this day in 1989.",
    (10, 16): "World Food Day was established by the United Nations on this day in 1945 to highlight the fight against hunger.",
    (10, 17): "The earliest known recipe for buttered bread — from Italy — dates to around this date in the 16th century.",
    (10, 18): "Thomas Edison patented the phonograph — the first device that could record and play back sound — on this day in 1877.",
    (10, 19): "Wikipedia, offering free knowledge to the world, was formally established on this day in 2003.",
    (10, 20): "The Sydney Opera House — one of the world's most distinctive buildings — officially opened on this day in 1973.",
    (10, 21): "Thomas Edison successfully tested the first practical incandescent lightbulb, burning for 13 hours, on this day in 1879.",
    (10, 22): "The Cuban Missile Crisis — 13 days the world feared nuclear war — began when Kennedy announced it on this day in 1962.",
    (10, 23): "The first chocolate recipe in Europe appeared in a Spanish document on this day in 1631.",
    (10, 24): "The United Nations was officially founded on this day in 1945, now with 193 member states.",
    (10, 25): "Pablo Picasso, who co-founded Cubism and painted Guernica, was born in Málaga, Spain on this day in 1881.",
    (10, 26): "The Erie Canal — connecting the Great Lakes to New York City and transforming American trade — opened on this day in 1825.",
    (10, 27): "Theodore Roosevelt, who established the US National Parks system, was born in New York City today in 1858.",
    (10, 28): "The Statue of Liberty was dedicated in New York Harbor on this day in 1886, a gift from France.",
    (10, 29): "Wall Street's 'Black Tuesday' stock market crash on this day in 1929 triggered the Great Depression.",
    (10, 30): "Orson Welles' radio dramatisation of War of the Worlds aired on this day in 1938, causing widespread panic.",
    (10, 31): "Halloween traces back to the Celtic festival of Samhain, celebrated on this night for over 2,000 years.",

    # ── November ───────────────────────────────────────────────────────────────
    (11,  1): "All Saints' Day — observed across many cultures — is the day people remember those who have passed on.",
    (11,  2): "North and South Dakota became the 39th and 40th US states simultaneously on this day in 1889.",
    (11,  3): "Laika the dog became the first living creature to orbit Earth aboard Sputnik 2 on this day in 1957.",
    (11,  4): "The tomb of Tutankhamun — the boy pharaoh — was discovered by Howard Carter in Egypt's Valley of the Kings today in 1922.",
    (11,  5): "Guy Fawkes Night commemorates the failed Gunpowder Plot of 1605, celebrated in Britain with bonfires and fireworks.",
    (11,  6): "The first American football game under college rules was played between Rutgers and Princeton on this day in 1869.",
    (11,  7): "Marie Curie — the first person to win two Nobel Prizes, in Physics and Chemistry — was born in Warsaw today in 1867.",
    (11,  8): "Wilhelm Röntgen discovered X-rays on this day in 1895, noticing that cathode rays made a fluorescent screen glow.",
    (11,  9): "The Berlin Wall fell on this day in 1989, reuniting East and West Germany after 28 years of division.",
    (11, 10): "Sesame Street — which has taught counting and letters to generations of children — first aired on PBS on this day in 1969.",
    (11, 11): "World War I ended at the 11th hour of the 11th day of the 11th month in 1918, with the Armistice taking effect.",
    (11, 12): "Auguste Rodin, sculptor of The Thinker and The Kiss, was born in Paris on this day in 1840.",
    (11, 13): "Robert Louis Stevenson, author of Treasure Island and Kidnapped, was born in Edinburgh today in 1850.",
    (11, 14): "Jawaharlal Nehru, India's first Prime Minister, was born in Allahabad on this day in 1889.",
    (11, 15): "The first electric tram in the world began service in Richmond, Virginia on this day in 1888.",
    (11, 16): "UNESCO, which protects world heritage sites and promotes global education, was founded on this day in 1945.",
    (11, 17): "The Suez Canal — connecting the Mediterranean Sea to the Red Sea — was officially opened on this day in 1869.",
    (11, 18): "Mickey Mouse made his sound-film debut in Steamboat Willie on this day in 1928.",
    (11, 19): "Indira Gandhi, the first female Prime Minister of India, was born in Allahabad on this day in 1917.",
    (11, 20): "The Nuremberg Trials — prosecuting Nazi war criminals — began on this day in 1945.",
    (11, 21): "The first controlled powered flight by a heavier-than-air aircraft was successfully completed on this day in 1903.",
    (11, 22): "John F. Kennedy was assassinated while riding in a motorcade in Dallas, Texas on this day in 1963.",
    (11, 23): "The first issue of Life magazine — pioneering photojournalism — was published on this day in 1936.",
    (11, 24): "Charles Darwin published On the Origin of Species on this day in 1859, the entire first print run selling out same day.",
    (11, 25): "Suriname became independent from the Netherlands on this day in 1975.",
    (11, 26): "The first Thanksgiving feast was shared by Plymouth colonists and the Wampanoag people around this date in 1621.",
    (11, 27): "Bruce McCandless made the first untethered spacewalk — flying freely in space with no lifeline — on this day in 1984.",
    (11, 28): "The first soccer international — England vs Scotland — ended 0-0 at Hamilton Crescent, Glasgow on this day in 1872.",
    (11, 29): "The first photograph of a person was captured in a Parisian boulevard by Louis Daguerre around this date in 1838.",
    (11, 30): "Mark Twain, author of Adventures of Huckleberry Finn and The Adventures of Tom Sawyer, was born today in 1835.",

    # ── December ───────────────────────────────────────────────────────────────
    (12,  1): "World AIDS Day has been observed on this day every year since 1988 to raise awareness and remember those lost.",
    (12,  2): "Napoleon crowned himself Emperor of France at Notre-Dame Cathedral in Paris on this day in 1804.",
    (12,  3): "Dr. Christiaan Barnard performed the world's first successful human heart transplant in Cape Town on this day in 1967.",
    (12,  4): "The world's oldest whisky distillery — Bushmills in Northern Ireland — received its licence on this day in 1608.",
    (12,  5): "Walt Disney, who created Mickey Mouse, Disneyland, and over 50 animated features, was born today in 1901.",
    (12,  6): "Finland declared independence from Russia on this day in 1917.",
    (12,  7): "The Japanese attack on Pearl Harbor brought the United States into World War II on this day in 1941.",
    (12,  8): "John Lennon was fatally shot outside his New York City apartment building by a fan on this day in 1980.",
    (12,  9): "The first Lego bricks were patented by Godtfred Kirk Christiansen on this day in 1958 — 'LEGO' means 'play well' in Danish.",
    (12, 10): "The Nobel Prizes are awarded every year on this date, the anniversary of Alfred Nobel's death in 1896.",
    (12, 11): "UNICEF — dedicated to protecting the rights and welfare of every child worldwide — was founded on this day in 1946.",
    (12, 12): "Kenya gained independence from British colonial rule on this day in 1963.",
    (12, 13): "The first ice hockey game played under organised rules took place in Montreal on this day in 1875.",
    (12, 14): "Roald Amundsen and his four-man team became the first explorers to reach the South Pole on this day in 1911.",
    (12, 15): "The Bill of Rights — the first ten amendments to the US Constitution — was ratified on this day in 1791.",
    (12, 16): "Ludwig van Beethoven, one of history's greatest composers, was baptised in Bonn on this day in 1770.",
    (12, 17): "The Wright Brothers made the first successful powered airplane flight at Kitty Hawk, North Carolina on this day in 1903.",
    (12, 18): "The 13th Amendment to the US Constitution, permanently abolishing slavery nationwide, was ratified on this day in 1865.",
    (12, 19): "The ancient Aztec Sun Stone (or 'Aztec Calendar') was discovered buried under Mexico City's main plaza on this day in 1790.",
    (12, 20): "Louisiana was purchased from France for $15 million — tripling the size of the United States — on this day in 1803.",
    (12, 21): "The winter solstice — the shortest day of the year in the Northern Hemisphere — typically falls on this date.",
    (12, 22): "Isaac Newton described the laws of universal gravitation in Principia Mathematica, submitted around this date in 1687.",
    (12, 23): "The transistor — the tiny switch that made modern electronics possible — was invented at Bell Labs on this day in 1947.",
    (12, 24): "Christmas Eve: Christmas trees were first used as decorations in Germany in the 16th century, popularised by Prince Albert in 1848.",
    (12, 25): "Isaac Newton was born in Woolsthorpe, England on Christmas Day in 1642 (Julian calendar).",
    (12, 26): "Boxing Day in Commonwealth countries — traditionally a day to give boxes of gifts to servants and the poor.",
    (12, 27): "The Radium element was discovered by Marie and Pierre Curie — named after Latin for 'ray' — on this day in 1898.",
    (12, 28): "The Lumière brothers screened the world's first commercial motion picture for a paying audience in Paris on this day in 1895.",
    (12, 29): "The first ice hockey game played under organised rules took place at Victoria Skating Rink, Montreal on this day in 1875.",
    (12, 30): "Rudyard Kipling, author of The Jungle Book and creator of Mowgli and Baloo, was born in Mumbai today in 1865.",
    (12, 31): "New Year's Eve: the tradition of dropping the ball in New York's Times Square began on this day in 1907.",
}


# ── Public API ────────────────────────────────────────────────────────────────

def get_today_history(dt: datetime) -> str:
    """
    Return the historical fact for the given date.
    Uses only the month and day of *dt* (year is ignored).
    Falls back to a generic message if no entry exists.
    """
    return HISTORY.get(
        (dt.month, dt.day),
        "Every day is a chance to make history — play SigmoCatClash!",
    )
